global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['petclinic:8080']
    metric_relabel_configs:
      - source_labels: [application]
        target_label: service_name
  
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
